version: '3'
services:
  myapp:
    image: st7ma784/runbertscoretest:latest

    volumes:
      - /data:/data
    restart: always
    #give access to the host's network
    # network_mode: "host"
    deploy:
      replicas: 3
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
      restart_policy:
        condition: any
