- title: 'LiSAScore - an incremental Improving of BERTScore'
  image: /assets/img/blocks/code-med.jpg
  description:
    - A demonstration that Linear Sum assignment removes double-counting in semantic-based metrics
    - Benchmarking translation and summarisation tasks against 6 common models including BERT,BART,Roberta,T5 and more.
  author:
    - Stephen Mander
    - Jesse Phillips
