FROM pytorch/pytorch:latest
RUN apt-get update
RUN apt-get -y install git
RUN pip install --upgrade pip --no-cache-dir
COPY requirements.txt /tmp/
RUN pip install --requirement /tmp/requirements.txt --no-cache-dir

WORKDIR /app
# COPY . /app needs to follow symlinks too
COPY . /app

# show the files in the container
#RUN ls -la /app
EXPOSE 5000/tcp

# run the app with gunicorn.sh
CMD ["bash", "gunicorn.sh"]

